#!/bin/sh
# This is the launcher script for GDM.
# It allows updating or downgrading GDM CLI through "gdm update-gdm <version>".
LAUNCHER_VERSION="1.3"

GDM_BASE="${HOME}/gazoo/gdm"
GDM_VIRTUAL_ENV="$GDM_BASE/virtual_env"
VE_GDM="$GDM_VIRTUAL_ENV/bin/gdm"
VE_PIP="$GDM_VIRTUAL_ENV/bin/pip3"


make_ve_if_not_exist()
{
  if [ ! -d "$GDM_VIRTUAL_ENV" ]; then
    echo "Creating GDM virtual environment $GDM_VIRTUAL_ENV"
    python3 -m virtualenv "$GDM_VIRTUAL_ENV"
  fi
}

install_or_update_gdm()
{
  local gdm_version="$1"
  make_ve_if_not_exist

  if [ -n "$gdm_version" ]; then
    "$VE_PIP" install --no-input -U "gazoo-device==$gdm_version"
  else
    "$VE_PIP" install --no-input -U gazoo-device
  fi
}

case $1 in
  -v)
    echo "Gazoo Device Manager launcher $LAUNCHER_VERSION"
    if [ -x "$VE_GDM" ]; then
      "$VE_GDM" "$@"
    fi
    ;;
  update-gdm|update_gdm)
    install_or_update_gdm "$2"
    ;;
  *)
    if [ -x "$VE_GDM" ]; then
      "$VE_GDM" "$@"
    else
      echo "GDM is not yet installed at $VE_BASE:" 1>&2
      echo "Use 'gdm update-gdm' or 'gdm update-gdm [version]' to install it" 1>&2
      exit 1
    fi
    ;;
esac
