# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: actions_service.proto
# pylint: skip-file
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x15\x61\x63tions_service.proto\x12\x08\x63hip.rpc\x1a\x0c\x63ommon.proto"\xa3\x01\n\x06\x41\x63tion\x12"\n\x04type\x18\x01'
    b' \x01(\x0e\x32\x14.chip.rpc.ActionType\x12\x0f\n\x07\x64\x65layMs\x18\x02'
    b' \x01(\r\x12\x10\n\x08\x61\x63tionId\x18\x03'
    b' \x01(\r\x12\x11\n\x04\x61rg1\x18\x04'
    b' \x01(\rH\x00\x88\x01\x01\x12\x11\n\x04\x61rg2\x18\x05'
    b' \x01(\rH\x01\x88\x01\x01\x12\x11\n\x04\x61rg3\x18\x06'
    b' \x01(\rH\x02\x88\x01\x01\x42\x07\n\x05_arg1B\x07\n\x05_arg2B\x07\n\x05_arg3"\\\n\x0e\x41\x63tionsRequest\x12\x13\n\x0b\x65ndpoint_id\x18\x01'
    b' \x01(\r\x12\x12\n\ncluster_id\x18\x02'
    b' \x01(\r\x12!\n\x07\x61\x63tions\x18\x03'
    b' \x03(\x0b\x32\x10.chip.rpc.Action*B\n\nActionType\x12\x13\n\x0fWRITE_ATTRIBUTE\x10\x00\x12\x0f\n\x0bRUN_COMMAND\x10\x01\x12\x0e\n\nEMIT_EVENT\x10\x02\x32@\n\x07\x41\x63tions\x12\x35\n\x03Set\x12\x18.chip.rpc.ActionsRequest\x1a\x12.pw.protobuf.Empty"\x00\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, 'actions_service_pb2', globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACTIONTYPE._serialized_start = 309
  _ACTIONTYPE._serialized_end = 375
  _ACTION._serialized_start = 50
  _ACTION._serialized_end = 213
  _ACTIONSREQUEST._serialized_start = 215
  _ACTIONSREQUEST._serialized_end = 307
  _ACTIONS._serialized_start = 377
  _ACTIONS._serialized_end = 441
# @@protoc_insertion_point(module_scope)
