# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: boolean_state_service.proto
# pylint: skip-file
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x62oolean_state_service.proto\x12\x08\x63hip.rpc\"(\n\x11\x42ooleanStateState\x12\x13\n\x0bstate_value\x18\x01 \x01(\x08\"B\n\x16\x42ooleanStateSetRequest\x12\x13\n\x0b\x65ndpoint_id\x18\x01 \x01(\r\x12\x13\n\x0bstate_value\x18\x02 \x01(\x08\"/\n\x17\x42ooleanStateSetResponse\x12\x14\n\x0c\x65vent_number\x18\x01 \x01(\x04\"-\n\x16\x42ooleanStateGetRequest\x12\x13\n\x0b\x65ndpoint_id\x18\x01 \x01(\r\"E\n\x17\x42ooleanStateGetResponse\x12*\n\x05state\x18\x01 \x01(\x0b\x32\x1b.chip.rpc.BooleanStateState2\xaa\x01\n\x0c\x42ooleanState\x12L\n\x03Set\x12 .chip.rpc.BooleanStateSetRequest\x1a!.chip.rpc.BooleanStateSetResponse\"\x00\x12L\n\x03Get\x12 .chip.rpc.BooleanStateGetRequest\x1a!.chip.rpc.BooleanStateGetResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'boolean_state_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOOLEANSTATESTATE._serialized_start=41
  _BOOLEANSTATESTATE._serialized_end=81
  _BOOLEANSTATESETREQUEST._serialized_start=83
  _BOOLEANSTATESETREQUEST._serialized_end=149
  _BOOLEANSTATESETRESPONSE._serialized_start=151
  _BOOLEANSTATESETRESPONSE._serialized_end=198
  _BOOLEANSTATEGETREQUEST._serialized_start=200
  _BOOLEANSTATEGETREQUEST._serialized_end=245
  _BOOLEANSTATEGETRESPONSE._serialized_start=247
  _BOOLEANSTATEGETRESPONSE._serialized_end=316
  _BOOLEANSTATE._serialized_start=319
  _BOOLEANSTATE._serialized_end=489
# @@protoc_insertion_point(module_scope)
